### ISSUE TITLE
Log enqueued but not sent

### ISSUE THREAD

**Issue by dmurty** [graffen/NLog.Targets.Syslog#116]
In testing the nlog.targets.syslog I noticed that if my test logged an exception that it never was received by the remote server. In the nlog.log file I saw that the message was being enqueued but never sent. I added a thread.sleep(5000); and the log server started to receive the logs. What can I do so an enqueued log can be guaranteed to be sent once its enqueued regardless of when the application terminated.

**Comment by VoicePulseKetan** [comment]
Also seeing this issue with NLog.Targets.Syslog v4.1.0. Tried with all other targets removed, setting async to true/false, both UDP/TCP. The internal logs show messages being enqueued, but they are only successfully sent at a rate of one every 0.5s. If I put in a 10s sleep at the end, 20 of the queued messages will get sent before the application terminates.

**Comment by VoicePulseKetan** [comment]
Adding <connectionCheckTimeout>0</connectionCheckTimeout> seems to mitigate the issue. Looks like it's not defaulting to 100us, but 500ms instead.

**Comment by luigiberrettini** [comment]
Hi @dmurty and @VoicePulseKetan it would be great if you could elaborate more on what is the scenario in which you are using this target and what is the expected behavior.

It would be also helpful if you can create a basic sample of what you are trying to do and give me the URL of the repo.

Please consider that NLog currently does not have an async API, therefore, being this target based on TPL, you cannot have a sync behavior.

As for the `connectionChecktimeout` I opened #117.
