### ISSUE TITLE
Clarify v3 changes

### ISSUE THREAD

**Issue by markdascher** [graffen/NLog.Targets.Syslog#64]
Noticed the following new behavior with v3:

* New configuration syntax.  May be worth clarifying whether or not NLog v2 is still supported, or if everyone should immediately switch to the latest v3.  Also, maybe it's just me, but [this](https://github.com/graffen/NLog.Targets.Syslog/blob/v3.0.2/src/TestApp/NLog.config) makes things seem more complicated than they really are, especially when compared to [its predecessor](https://github.com/graffen/NLog.Targets.Syslog/blob/v2.1.6030.21112/src/TestApp/NLog.config).  =)
* My "Hello World" test program needs an explicit sleep at the end.  NLog v2 seemed to be a bit more synchronous, at least for the initial TCP connection and TLS negotiation.  My assumption was that, if we wanted it to be asynchronous, we'd put it in an AsyncWrapper.

I like the new syntax, now that I'm used to it.  But the changes seemed to come out of nowhere, for those of us not keeping up on these commits.  A brief changelog in the README would probably help, even if it just says that the v2 syntax won't work with v3.  And possibly something about whether AsyncWrapper is no longer (or never was) needed.

**Comment by luigiberrettini** [comment]
Sorry that you are finding these issues.

Using semantic versioning, I increased the major version to indicate there were breaking changes and I used GitHub features for [release notes](https://github.com/graffen/NLog.Targets.Syslog/releases)

Not having a persistent 2.x branch should suggest version 2 is no more supported, anyway I will try to make the readme more explicit.

As for the test application, it is meant to test multiple scenarios, therefore a complex app.config is needed: a much simpler configuration file example is in the readme, but I will try to show some more sample configurations.

With regards to the AsyncWrapper it is not suited for what the Syslog target needs and I will make it clear in the readme. Being asynchronous is usually an advantage, but to allow more control we should have a totally async implementation of NLog so that you could wait on a logging call when needing sync operations. The need for async arose when an issue was opened asking for persistent TCP or UDP connections to avoid slowing down the caller.
Async tasks should be canceled as soon as the target is disposed: if you have a console app and your main method doesn't wait for user input that's maybe the reason why you need to sleep.

**Comment by markdascher** [comment]
Thanks for the answer!  It all makes sense, and this is still my favorite syslog library.  =)
