### ISSUE TITLE
Change Syslog target at runtime

### ISSUE THREAD

**Issue by StasLivshits** [graffen/NLog.Targets.Syslog#82]
I'm trying to change the target from the code, but the Logger keep sending to the old destination.
Here is the code:

var syslogTarget = (NLog.Targets.Syslog.SyslogTarget)LogManager.Configuration.FindTargetByName("SyslogTarget");
syslogTarget.MessageSend.Udp.Server = "127.0.0.1";
LogManager.ReconfigExistingLoggers();
LogManager.Flush();

Note: changing another target (file target) works that way.

Any thoughts?

**Comment by MoYummy** [comment]
Here is my code in old version of syslog. Hope it helps.

~~~
var config = LogManager.Configuration;
var syslogTarget = config.FindTargetByName<Syslog>(CNSTR_SYSLOG);
syslogTarget.SyslogServer = "some.syslog.server";
LogManager.Configuration = config;
LogManager.Configuration.Reload();
LogManager.ReconfigExistingLoggers();
~~~

**Comment by luigiberrettini** [comment]
I just created a console application and found out that both the ColoredConsoleTarget and FileTarget behave as expected without reloading the configuration or reconfiguring loggers:
```csharp
var coloredConsoleTarget = loggingConfiguration.FindTargetByName<ColoredConsoleTarget>(ColoredConsoleTargetName);
coloredConsoleTarget.Layout = "${message}";

var fileTarget = loggingConfiguration.FindTargetByName<FileTarget>(FileTargetName);
fileTarget.FileName = ".\\new-log.txt";
```

This is because those targets use target properties directly instead of loading them from configuration settings.

I thought that the InitializeTarget was called to reconfigure a target, but if it is already inited no reconfig happens 😞

I could simply add a ReInitialize method but I would prefer not breaking the NLog base Target API.
Moreover I would like to avoid adding a Reinit call to each and every configuration setter.

Maybe a ForceReinit or ReconfigExistingLoggers(force: true) would be useful...
Does @304NotModified have any suggestion on the expected behavior a target with complex configuration should have and a feasible and elegant solution?

**Comment by 304NotModified** [comment]
Isn't easy to reset the cached values in the setter?

Eg in the `set` of Server property, clear the current connection. IPropertyChanged is maybe a nice pattern.

**Comment by luigiberrettini** [comment]
Ok I think I will use INotifyPropertyChanged, but it will require a bit of effort
