### ISSUE TITLE
Outdated schema

### ISSUE THREAD

**Issue by strigare** [graffen/NLog.Targets.Syslog#92]
The schema at http://nlog-project.org/schemas/NLog.Targets.Syslog.xsd is no longer valid after your last update which changed the way TLS works. This is particularly troublesome because there is documentarion around the web that uses the prior way (for example: http://help.papertrailapp.com/kb/configuration/nlog-net-logging/).

I understand it's probably not your responsability, but thought I should let you know. It took me a while to make the library work because of this :P

**Comment by luigiberrettini** [comment]
Thanks, I already submitted a PR, but the problem is new releases and the schema on the NLog site are not published in a "transactional" way: if a new schema is published on the NLog site and not a new release we still have a problem.

Moreover the NLog site only has the latest version and this is the only sustainable way to publish on a site without making users change xmlns every time.

The best solution would be to update the NuGet package of both the target and the schema 😉
